export const ALL_CONTACTUS_REQUEST = "ALL_CONTACTUS_REQUEST";
export const ALL_CONTACTUS_SUCCESS = "ALL_CONTACTUS_SUCCESS";
export const ALL_CONTACTUS_FAIL = "ALL_CONTACTUS_FAIL";

export const ADMIN_CONTACTUS_REQUEST = "ADMIN_CONTACTUS_REQUEST";
export const ADMIN_CONTACTUS_SUCCESS = "ADMIN_CONTACTUS_SUCCESS";
export const ADMIN_CONTACTUS_FAIL = "ADMIN_CONTACTUS_FAIL";

export const CONTACTUS_DETAILS_REQUEST = "CONTACTUS_DETAILS_REQUEST";
export const CONTACTUS_DETAILS_SUCCESS = "CONTACTUS_DETAILS_SUCCESS";
export const CONTACTUS_DETAILS_FAIL = "CONTACTUS_DETAILS_FAIL";

export const NEW_CONTACTUS_REQUEST = "NEW_CONTACTUS_REQUEST";
export const NEW_CONTACTUS_SUCCESS = "NEW_CONTACTUS_SUCCESS";
export const NEW_CONTACTUS_FAIL = "NEW_CONTACTUS_FAIL";
export const NEW_CONTACTUS_RESET = "NEW_CONTACTUS_RESET";

export const DELETE_CONTACTUS_REQUEST = "DELETE_CONTACTUS_REQUEST";
export const DELETE_CONTACTUS_SUCCESS = "DELETE_CONTACTUS_SUCCESS";
export const DELETE_CONTACTUS_FAIL = "DELETE_CONTACTUS_FAIL";
export const DELETE_CONTACTUS_RESET = "DELETE_CONTACTUS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
