export const ALL_GST_REQUEST = "ALL_GST_REQUEST";
export const ALL_GST_SUCCESS = "ALL_GST_SUCCESS";
export const ALL_GST_FAIL = "ALL_GST_FAIL";

export const NEW_GST_REQUEST = "NEW_GST_REQUEST";
export const NEW_GST_SUCCESS = "NEW_GST_SUCCESS";
export const NEW_GST_RESET = "NEW_GST_RESET";
export const NEW_GST_FAIL = "NEW_GST_FAIL";

export const UPDATE_GST_REQUEST = "UPDATE_GST_REQUEST";
export const UPDATE_GST_SUCCESS = "UPDATE_GST_SUCCESS";
export const UPDATE_GST_RESET = "UPDATE_GST_RESET";
export const UPDATE_GST_FAIL = "UPDATE_GST_FAIL";

export const DELETE_GST_REQUEST = "DELETE_GST_REQUEST";
export const DELETE_GST_SUCCESS = "DELETE_GST_SUCCESS";
export const DELETE_GST_RESET = "DELETE_GST_RESET";
export const DELETE_GST_FAIL = "DELETE_GST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
