export const NEW_VIDEO_REQUEST = "NEW_VIDEO_REQUEST";
export const NEW_VIDEO_SUCCESS = "NEW_VIDEO_SUCCESS";
export const NEW_VIDEO_RESET = "NEW_VIDEO_RESET";
export const NEW_VIDEO_FAIL = "NEW_VIDEO_FAIL";

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL";

export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_RESET = "DELETE_VIDEO_RESET";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
